### ISSUE TITLE
About MegaClient Sense port

### ISSUE THREAD

**Issue by xxjerryxx1983** [toyoshim/iona#10]
FIrst of all, thank you for bring us such nice program, I really appreciate it.
I'm wondering if that the JVS sense port in ArduinoMega client is correct, because the OC2B port on board is D9, not D3 port mentioned in file, and neither 2 ports are not effective for the game.
The "JVS connect error" will happen when I enter the TTX game(SF4 AE, KOF98Um), please tell me the correct port of the sense signal, thank you very much.

// Data+: 2 PD2 ( RXDI/INT2 )
// Data-: 3 PD3 ( TXD1/INT3 )
using MegaDataClient = BaseDataClient<0, 1, 0, 1, 0x0e, 0x0e>;

// Sense: 3 (PWM OC2B - RC LPF of 100nF, 100Ω is needed to generate 2.5V)
using MegaSenseClient = BaseSenseClient<3>;
![微信图片_20201114203017](https://user-images.githubusercontent.com/74454044/99147029-5497bb00-26b8-11eb-8abb-cebfeb511861.jpg)

**Comment by toyoshim** [comment]
Thank you for your report, and sorry for the late reply.

> I'm wondering if that the JVS sense port in ArduinoMega client is correct, because the OC2B port on board is D9, not D3 port mentioned in file, and neither 2 ports are not effective for the game.

> // Sense: 3 (PWM OC2B - RC LPF of 100nF, 100Ω is needed to generate 2.5V)
> using MegaSenseClient = BaseSenseClient<3>;

You are right. It's a bug. We should use D9 for the SENSE port. So, the using line should be BaseSenseClient<9>;.
Also, the D9 is used for 1P button2 by default in the IONA. So, we need to replace it with another available pin.

I will submit a speculative fix for this though I'm not ready for testing this on mega2560.

**Comment by toyoshim** [comment]
Can you check the latest revision?
I fixed the jvsio library to use pin9 for sense on mega.
Also, pin assignment for the mega is changed in iona.ino.
