### ISSUE TITLE
Service button

### ISSUE THREAD

**Issue by kimaq** [toyoshim/iona#12]
Hi,

I'm testing your project on Arduino Nano. It's working great but as I can see for this board there's no Service button handling.
I'll switch to Mega if needed but is it possible to do it on Nano?

  //       START       SERVICE     UP          DOWN        LEFT        RIGHT       PUSH1       PUSH2
    ios[1] = in( 2, 7)    ???    | in( 3, 5) | in( 4, 4) | in( 5, 3) | in( 6, 2) | in( 7, 1) | in( 8, 0);

Kind Regards,
Peter

**Comment by toyoshim** [comment]
Well, A4 and A5 are still free on the nano.
So, you can put one of them into pins[] array, and use the IO for the service button.

> const int pins[] = {
>  12, A3,
>  A2,  4,  5,  6,  7,  8,  9, 10, 11, A1, A0,
>  A4,  // please put this into the end of the array as other indices worked as they did.
>};

'in(13, 6)' should be inserted for ios[1]. '13' means the A4 is placed at 13th (0 origin) in the pins. '6' means service button here.

> ios[1] = in( 2, 7) | in(13, 6) | in( 3, 5) | in( 4, 4) | in( 5, 3) | in( 6, 2) | in( 7, 1) | in( 8, 0);

I haven't verified these code, but probably it works.

**Comment by kimaq** [comment]
Thanks,
It's working now. But now as I can access input test mode I noticed that some inputs are triggering another inputs.
For example holding SW1 I get solid "ON" on JVS test screen.
But holding SW3 I get constantly ON/OFF for SW3 and for SW2 as well. It's the same for most other inputs.
Do you know what can be wrong? I've checked the wiring and it looks good. My nano is a clone, maybe that is a problem?

**Comment by toyoshim** [comment]
Did you edit following lines correctly?
> //#define USE_NANO
> #define USE_MEGA

Default code isn't for Nano, but for MEGA2560.

Also, can you check if the unstable input issue disappears when you remove updateMode() call at line 166?

**Comment by kimaq** [comment]
Thanks again,

removing updateMode() solved the issue:) I can finally play my Naomi outside the cabinet.
