### ISSUE TITLE
missing push button 2 for two player mode on Mega

### ISSUE THREAD

**Issue by mikebrandt** [toyoshim/iona#13]
Hi,
 i tried to compile iona for Mega and i think that push button 2 for player 2 is missing in io def at line 117. Am i reading code wrong?

Best regards,
Mike

**Comment by toyoshim** [comment]
I guess you meant line 177.
This is just a source formatting issue. The service button isn't assigned for the player 2 (as same as player 1), and it results in that we have just 7 `in(n, m)` in the line. So, that should be fine.
I will submit a format fix change.

**Comment by toyoshim** [comment]
https://github.com/toyoshim/iona/commit/65986f8bb2548e6de19828708844f9878198d156
Hope this CL explains better than my words above.
