### ISSUE TITLE
Naomi detection issues

### ISSUE THREAD

**Issue by system11b** [toyoshim/iona#16]
I have a V2 Iona which was only recently purchased and I believe has 1.3x firmware installed.  It works with Ringedge2 and Exa systems, but my Naomi 1 doesn't recognise it - the blue LED never stops flashing, test mode cannot see any JVS nodes, and starting a game gives JVS IO not connected errors.  I have tried multiple USB(JVS) and power cables right down to the shortest available - these did not make a difference.  The Naomi works fine with Capcom and Sega JAMMA-JVS converters so I assume it is working correctly.

There are a few people with the same issue on the arcade projects forum:
https://www.arcade-projects.com/threads/mp07-iona-us-jvs-usb-i-o-board-worldwide-sales-troubleshooting-thread.20112/page-11

**Comment by system11b** [comment]
I solved the problem, kind of.

I had to upgrade the firmware from 1.35 to 1.42d, even after upgrade it was not detected until I used the new options mode to inactivate the JVS signal adjustment.  I have a question - what does this option actually do?  Will it potentially cause harm to other hardware (for example my Exa) by sending a high signal, or is it the other way around and disabling a boost?  I repeated the test several times, with the signal adjustment enabled (default dip 3) it always fails, with dip 3 on to disable adjustment it is reliable both in BIOS and Game modes.

I also had a problem with WinUSB and getting "This device cannot start. (Code 10)" when trying to install the WinUSB driver.
I did a bunch of testing, it's simply not compatible with some USB ports. It doesn't work on the built in USB-A (3.1) ports on my Lenovo X1 gen 4, but it's fine with a couple of cheap unpowered USB-C hubs/adapters - for example the Unigreen USB-C to Ethernet dongle which has 3x USB-A (3.1) ports. That works perfectly.

**Comment by mobiusstriptech** [comment]
Same issue here. Worked just fine on both my NAOMI 2 but neither of my NAOMI 1 would work with the device. I ended up doing the same thing you did and upgrading the firmware, then disabling the JVS signal adjustment. For those with Xbox controllers button 3 is B, just to help you figure that out.

I wish there was an easier way to disable/enable this. Figuring out how to get to the options menu is tricky. Once I figured out that I had to hold test and service for .5 seconds, then press service, then press test 2 times, then hold down B on my controller when pressing test again for the 3rd time, it worked great. Hope that explanation helps others.

Could we have this option disabled by default? Or maybe hold test on power on to enable/disable?

**Comment by toyoshim** [comment]
Hi, this is a repository for an Adruino-based IONA, and what you are talking about is IONA-US, and the repository is https://github.com/toyoshim/iona-us/issues

**Comment by toyoshim** [comment]
Reg the signal adjustment option, it doesn't affect sending signals, but affects receiving ones as some device's neg signal is really higher, e.g. 1.7V, than the threshold for the 3.3V based IONA's microcontroller. So this is an option to activate voltage divider for receiving signals.

This compatibility troubles happen because IONA-US could not cover all possible valid range of EIA-RS485 but signal's characteristics vary board by board.

**Comment by toyoshim** [comment]
Also, the signal compatibility issue is explained in the official document at the compatibility section.
https://toyoshim.github.io/iona-us/en

Your experience around WinUSB's trouble shooting would be helpful for other users. I'll update the page with your information.

**Comment by toyoshim** [comment]
To mobiusstriptech:
Having another easy option to flip the mode sounds a good idea. But I don't want to change the default mode as more devices are compatible with this flag being enabled.

**Comment by toyoshim** [comment]
Let me close this thread as this issue doesn't happen on Arduino based IONA as AVR runs at 5V.
Feel free to open new issue for iona-us.

**Comment by toyoshim** [comment]
@mobiusstriptech please check the latest firmware as it contains the feature you requested, booting with TEST pressed will flip the signal adjust option.

**Comment by mobiusstriptech** [comment]
Loaded the new firmware and tested using Test button to flip the JVS signal off and on. It works great! Excellent addition to the firmware!
