### ISSUE TITLE
two player

### ISSUE THREAD

**Issue by itslemcy** [toyoshim/iona#4]
hi, great work first of all.
i was wondering if it is possible with an arduino with a lot of gpios such as the mega2650, to have a two player input.
thanks a lot!

**Comment by toyoshim** [comment]
sorry for the late answer.
yep, the sample code includes mega2560 support and I think it works with 2P support though I haven't verified on the real board yet.
just fyi, the underlying library, jvsio now supports multiple nodes within a single microcontroller. that says now it's possible to support 2 nodes x 2 players = 4 players in total if gpio allows. of course, 1 node x 4 players configuration would be possible.
