### ISSUE TITLE
Only two buttons working

### ISSUE THREAD

**Issue by cyllboy** [toyoshim/iona#7]
I'm testing with a Naomi 2 board, I have only two buttons working. Up down left right, player 1 start and player 1 coin are ok. Only fire buttons A and B work. Checked twice the connections but are a ok and tested with multimeter.

I'm pulling down A7 with 10K ohm resistor to simulate dip switch off.

Do you have any suggestions?

**Comment by toyoshim** [comment]
oops!
sorry, it seems my last commit mistakenly added a bug.

> 221:          io.pushReport(index < sizeof(index) ? ios[index] : 0x00);

This line should be

> 221:          io.pushReport(index < sizeof(ios) ? ios[index] : 0x00);

I will submit a fix soon.

**Comment by toyoshim** [comment]
submitted!
can you try with the the latest revision?

sorry for bothering you.

**Comment by cyllboy** [comment]
The latest version works very well! Now all the 6 buttons are ok!
Thank you very much!

**Comment by toyoshim** [comment]
Good to hear that my fix works, and thanks again for letting me know this issue.

Regarding the compiler warnings, I guess you are using a little old Arduino IDE.
With my 1.8.12 on mac, iona compiles without any warning. Maybe due to no or poor C++11 support in early Arduino IDE?

**Comment by cyllboy** [comment]
I had 1.8.12 but I'm using windows; now I updated to 1.8.13, but  warnigs did not go away.

At first installation, the warnings are covered by the code windows... and I didn't see them in windows because the lasting message was the OK thing: "Lo sketch usa 5306 byte (17%) dello spazio disponibile per i programmi. Il massimo è 30720 byte.
Le variabili globali usano 1030 byte (50%) di memoria dinamica, lasciando altri 1018 byte liberi per le variabili locali. Il massimo è 2048 byte." (My installation is Italian) 

Did you tried to enlarge the debug portion of the window?

Here is what I see: https://www.cyllenius.net/Screenshot%202020-08-16%2009.53.03.png

Then I opened better the window and I could see that the warnings were still there. They are these:
"
H:\Desktop\iona\iona.ino: In function 'setup':
H:\Desktop\iona\iona.ino:142:19: warning: iteration 15 invokes undefined behavior [-Waggressive-loop-optimizations]
     pinMode(pins[i], INPUT_PULLUP);
             ~~~~~~^
H:\Desktop\iona\iona.ino:141:21: note: within this loop
   for (int i = 0; i < sizeof(pins); ++i)
                   ~~^~~~~~~~~
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\main.cpp: In function 'main':
H:\Desktop\iona\iona.ino:142:19: warning: iteration 15 invokes undefined behavior [-Waggressive-loop-optimizations]
     pinMode(pins[i], INPUT_PULLUP);
                   ^
H:\Desktop\iona\iona.ino:141:21: note: within this loop
   for (int i = 0; i < sizeof(pins); ++i)
"

I don't know if this is a problem with my current computer where I installed in the time various versions of the IDE... I will try on a fresh computer that never had Arduino IDE on and I will report better.

**Comment by cyllboy** [comment]
I confirm the same behaviour on a fresh laptop... The warings are generated, than they "roll out of sight" during compilation.

Probably the C++ support is very weak in windows version.

The warnigs go away if the loop is not used, but so the code should be taylored on the number of pin used on the specific device, leaving less freedom. What do you think?

**Comment by toyoshim** [comment]
oops, compiler is correct. there is a buffer-overflow bug.
the loop should be "i < sizeof(pins) / sizeof(int)".

I'm on mac. probably installed AVR compiler version is different among Windows and mac.

I'll update it.

**Comment by toyoshim** [comment]
done!

**Comment by cyllboy** [comment]
Y*O*U* A*R*E* G*R*E*A*T*!!!!!!!!!!!!!!!!!!!!!!! =b
